### ISSUE TITLE
Calculated totals as a row

### ISSUE THREAD

**Issue by k5o** [GriddleGriddle/Griddle#103]
I'm not sure if this is within the scope of Griddle but it would be great to have a way to set a "Total" row that sums or averages integer/float columns from the grid.

I currently calculate my total figures separately and append it as the last `tr` row of my Griddle `table`  element, however this doesn't work if search/filters are used to truncate/filter through the initial data.

**Comment by ryanlanciaux** [comment]
Hey @k5o -- Sorry about the extreme delay in responding to this issue. This is not something we're planning to tackle just yet as a fix but the next major release of Griddle should be able to handle this scenario.

**Comment by ryanlanciaux** [comment]
Griddle now supports plugins that could wrap up this functionality. [Please check out the plugins docs](http://griddlegriddle.github.io/Griddle/docs/plugins/) and if this is still something you're looking to do (I realize some time has gone since this issue was posted 😄), please let us know if you have any trouble.
