### ISSUE TITLE
props.columns not updated

### ISSUE THREAD

**Issue by olethanh** [GriddleGriddle/Griddle#113]
Hi,
it seems the props.columns is not updated after the initial Mount.

In my react application I would like to have links to switch between hardcoded sets of columns however it seems that if you modify the columns props the changes aren't repercuted since Griddle only use its internal filteredColumns state from now on.

I guess the proper way would be for Griddle to detect when the props change and modify state.filtredColumns? Or is there any other way to do it?

**Comment by olethanh** [comment]
I have found a way to do this using refs and setColumns but I think this is still an issue, Griddle should either update when changing props.columns or it should be documented that it doesn't happen (maybe rename the property defaultColumns then?).

**Comment by vkurchatkin** [comment]
+1. This is very unexpected. I had to force component remount using `key` to solve this

**Comment by ryanlanciaux** [comment]
This should be fixed in the source but not up in npm just yet.

**Comment by jjstrat3** [comment]
@ryanlanciaux The fix for this issue seems to prevent changes to the filteredColumns array persisting once `componentWillRecieveProps` is triggered.  If changes were made via the gridSettings component, they are reverted to the default's that were set via the columns prop in situations like updated external results or `onRowClick`.
