### ISSUE TITLE
Use tfoot for pager component

### ISSUE THREAD

**Issue by andr83** [GriddleGriddle/Griddle#117]
I think it's better to use tfoot element for pagingContent. 

Now if use bootstrap styling like this: "table table-striped table-hover" pager also will apply it.

**Comment by ryanlanciaux** [comment]
Thanks for submitting this issue and I realize it's been quite some time since you posted but with the new architecture, we recommend doing this sort of thing through [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) or [as a plugin](http://griddlegriddle.github.io/Griddle/docs/plugins/). 👍
