### ISSUE TITLE
is there a plan to add column resizing?

### ISSUE THREAD

**Issue by airwin** [GriddleGriddle/Griddle#129]
May griddle have column resizing like facebook's [fixedDataTable](https://github.com/facebook/fixed-data-table)?

**Comment by joellanciaux** [comment]
This is going to be something we're shooting for in the next few versions of Griddle that are on the horizon. 

This has popped up in a few other areas, but we're currently updating some of the 'core' areas of Griddle to allow it to be a little more extensible without getting incredibly messy, so I'll be moving forward with this in mind. Most of the movement on that end is happening in the [griddle-core repo](https://github.com/GriddleGriddle/griddle-core).

Thanks for the suggestion!

**Comment by airwin** [comment]
Thank you, expecting~

**Comment by thellimist** [comment]
when will this feature be released

**Comment by aadrian** [comment]
Any news on the column re-sizing feature? Any real world use case of grids requires the possibility of resizing :( .

Thank you.

**Comment by ryanlanciaux** [comment]
This is not something that we've been able to tackle but we'd love to see this as a plugin in the new component architecture if anyone wants to give it a shot. Please see the [plugins section](http://griddlegriddle.github.io/Griddle/docs/plugins/) for more info on how this would work. 

Going to close this one for now since it's a little outside the scope of what we want to add to Griddle at this point. Thanks 👍
