### ISSUE TITLE
start the subgrid expanded

### ISSUE THREAD

**Issue by yordis** [GriddleGriddle/Griddle#156]
Currently we don't have the ability to start the subgrids expanded.

**Comment by yordis** [comment]
@kevinold can you review this please. Long time ago I changed the way it works for me but rather than just have some config like that, global config, this should be inside the dataset like we do with children configuration but this works at some point until we actually need to expand just some subgrid.


https://github.com/yordis/Griddle/commit/712693db2c3925fa6f60c8930ea541440419dcdb

**Comment by kevinold** [comment]
Yes I will be revising in the next day or two. 



On July 14, 2015 at 11:07:06 AM CDT, Yordis Prieto <notifications@github.com> wrote:@kevinold can you review this please. Long time ago I changed the way it works for me but rather than just have some config like that, global config, this should be inside the dataset like we do with children configuration but this works at some point until we actually need to expand just some subgrid.  yordis@712693d   —Reply to this email directly or view it on GitHub.

**Comment by sorenhoyer** [comment]
Any update on this?

**Comment by yordis** [comment]
@sorenhoyer @kevinold I made a PR long time ago but no response :cry:

**Comment by ryanlanciaux** [comment]
Sorry for the super long delay in this. We've made the decision to make the latest version of Griddle do less out-of-the box but provide extension points through [customization](http://griddlegriddle.github.io/Griddle/docs/customization/) or as [plugins](http://griddlegriddle.github.io/Griddle/docs/plugins/).

Closing for now but if anyone wants to take on writing a plugin -- we'd love to help.
