### ISSUE TITLE
can't use 'onRowClick' prop on customRowComponent

### ISSUE THREAD

**Issue by tuxiang79** [GriddleGriddle/Griddle#162]
Should pass the  'onRowClick' prop to the 'CustomRowComponentContainer'  component and 'customRowComponent' component 

griddle.jsx.js: 
React.createElement(CustomRowComponentContainer, { data: data, columns: cols, metadataColumns: meta,
                className: this.props.customRowComponentClassName, customComponent: this.props.customRowComponent,
                style: this.getClearFixStyles(), onRowClick: this.props.onRowClick }),

customRowComponentContainer.jsx.js
    var nodes = this.props.data.map(function (row, index) {
      return React.createElement(that.props.customComponent, { data: row, metadataColumns: that.props.metadataColumns, key: index, onRowClick: that.props.onRowClick });
    });

**Comment by ryanlanciaux** [comment]
Hi there and sorry about the extreme delay in following up on this one! In the latest version of Griddle we've made it possible for just about every component to be passed in as a prop and would recommend that a Row component that overrides the default Griddle row be used instead of the `CustomRowComponent` from v0. The user defined Row component could handle events like onRowClick

Please [see the customization docs](http://griddlegriddle.github.io/Griddle/docs/customization/) for more information on this. Thanks 👍
