### ISSUE TITLE
Is 'customComponent'  could be shown to user by double-click on cell instead of initial drawing?

### ISSUE THREAD

**Issue by deser** [GriddleGriddle/Griddle#173]
As it shown in image ( https://monosnap.com/file/uIPiIK2v523hRwZAFJMCHRssfcDzrm ) I have requirements for grid not to render custom component initially but render one of them be doubleclicking on cell. Is it possible within griddle?

**Comment by aphillipo** [comment]
Sure, you can do this the same way you'd build any component.  Custom components are just that react classes.

So therefore a double click to edit could be done by changing the state of the component on double click and changing it again after save (which happens on blur).

export default React.createClass({
    getInitialState: function() { return { editing: false }; },
    onDoubleClick: function(e) {
        this.setState({editing: true});
    },
    saveWithAjaxCallToBackend: function() {
       // fill in with saving code.
    }
    render() {
        var cellContents = this.props.data; // passed by griddle.
        if(this.state.editing) {
              cellContents = <input type="text" name={'prefix-row-id-' + this.props.rowData.id} value={cellContents} onBlur={this.saveWithAjaxCallToBackend} />
        }

        return 
              <div className="customCell {editingClass}" onDoubleClick={this.onDoubleClick}>
              {cellContents}
              </div>
    }
});

**Comment by aphillipo** [comment]
This input might need to be focused a few milliseconds after it appears, maybe with a set timeout...  Check what other javascript does.

**Comment by mohak1990** [comment]
where should i put this code?

**Comment by ryanlanciaux** [comment]
I realize some time has gone on here since this issue was active but we have released a new version of Griddle that introduces customization features that should make this quite a bit easier. Please see the [customization section](http://griddlegriddle.github.io/Griddle/docs/customization/) of the new docs for more info on how you could do this. 

How I would approach this is to make a custom column component that responds to the click events and changes how the data is rendered based on whether or not the cell has been clicked. If this was needed for all Cells, it may be good to consider providing a custom cell component for Griddle to use, or wrapping this behavior in [a plugin](http://griddlegriddle.github.io/Griddle/docs/plugins/). Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍
