### ISSUE TITLE
server-side rendering react-id mismatch

### ISSUE THREAD

**Issue by frankleng** [GriddleGriddle/Griddle#192]
copied code straight from the example, and hard-coding the data array
the component renders fine, but getting the follow error from the console.

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) .2.0.0.0.1.$grid_row1-container"><td sty
 (server) .2.0.0.0.1.$grid_row4-container"><td sty
```

The warning doesn't happen at the very first page load, but once upon refresh I can see the react-id of the server side component change... ex. 2.0.0.0.1.$grid_row7-container 
while the frontend version stays constant as "2.0.0.0.1.$grid_row1-container"

Is this a bug in griddle?

**Comment by leiming** [comment]
+1

**Comment by mihirsoni** [comment]
Yup it seems the counter is not reseting while refreshing the page so it turns out to be invalid checksum. Any work around for this ?

**Comment by chenrozenes** [comment]
+1

**Comment by utkuturunc** [comment]
+1

Any ideas on solutions/workarounds?

**Comment by utkuturunc** [comment]
`const rowMetadata = {
  key: 'id'
};`

`        <Griddle
          ...
          rowMetadata={rowMetadata}
          ...
        />`

**Comment by ryanlanciaux** [comment]
I know it's been quite awhile since this issue is opened but this should no longer be an issue with the latest version of Griddle. We've changed things around quite a bit and if nothing else, there are [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) That would allow for changing out the Row component used in Griddle with a Row component you provide without forking Griddle. [See the customization section](http://griddlegriddle.github.io/Griddle/docs/customization/) for more on how to do that if needed.

I'm going to close this one for now but please feel free to open a new issue if any problems are encountered. 👍
