### ISSUE TITLE
tr:nth-child(even) not working properly when enableInfiniteScroll is true

### ISSUE THREAD

**Issue by 0mc** [GriddleGriddle/Griddle#194]
Hi guys,

I have such a table row even/odd css setup:

table.potTable tr:nth-child(even) {
    background: #efefef;
}

table.potTable tr:nth-child(odd) {
    background: #ffffff;
}

When I config enableInfiniteScroll to true, the initial page looks fine. But after I start scrolling, the css setup not working any more. That's because there's an 'aboveSpacerRow'(line 1325 in griddle.js)  unshift into the table body which makes the first visible table row no longer be the first tr any more.

My solution to work around it is to check the 'height' of 'aboveSpacerRow', only unshift it if the height greater than zero. Which is working for me at the moment. My hack around code as below:

// Add the spacer rows for nodes we're not rendering.
if (aboveSpacerRow && parseFloat(aboveSpacerRow.props.style.height) > 0) {
    nodes.unshift(aboveSpacerRow);
}

Can you guys put in a fix for this issue?

Cheers,
Max

**Comment by aphillipo** [comment]
Why not just do tr:nth-child(2n+1) - usually odd but now means even - or tr:nth-child(2n) - which would now be odd?

I do wonder if the table should be spaced out with margin for infinite scrolling or a div instead.

I'm surprised your table rows are aligned with griddle as I'm getting issues with the version from github at least:

https://github.com/GriddleGriddle/Griddle/issues/141

**Comment by 0mc** [comment]
tr:nth-child(2n+1) doesn't work, because the 'aboveSpacerRow' won't be
inserted when the initial page load. The 'aboveSpacerRow' only be inserted
when you start scrolling.

The alignment issue you mention about I need to twist around it to make it
works for me. But you are right, fixed table heading not working properly
in current version as well.

**Comment by aphillipo** [comment]
I'd probably just add a class to alternating table rows then.  Old school.

You can do this with rowMetadata and bodyCssClassName which can be a function that taking in the row data.

**Comment by ryanlanciaux** [comment]
This will not work with the virtual scrolling plugin since we need to use spacer rows to get the scrollbars to appear correctly. We're evaluating what to do moving forward and if there's any way around this but I would recommend using the new [styling](http://griddlegriddle.github.io/Griddle/docs/styles/) API and/or [customization](http://griddlegriddle.github.io/Griddle/docs/customization/) options to get the desired effect. 

Closing this one for now as there is a workaround through the customization options and this is necessary for the virtual scrolling plugin. 👍
