### ISSUE TITLE
Use browser scrollbar

### ISSUE THREAD

**Issue by alolis** [GriddleGriddle/Griddle#196]
Hello,

I am wondering if it's possible to make a Griddle container, more specifically the infinite scroll version, to use the browser scrollbar instead of it's own container scrollbar.

Thank you for your time

**Comment by AlanFoster** [comment]
:+1:

**Comment by bkrall** [comment]
👍

**Comment by ryanlanciaux** [comment]
I know some time has gone on since this issue was opened but this should be possible with the latest Griddle as a [user / community plugin](http://griddlegriddle.github.io/Griddle/docs/plugins/). This sounds like it's great functionality but not something we're planning on shipping as part of the base Griddle component.

Thanks for the discussion on this but closing this one fore now 👍
