### ISSUE TITLE
Retrieve Filtered Rows

### ISSUE THREAD

**Issue by raybooysen** [GriddleGriddle/Griddle#209]
Once filtering has occurred, there doesn't seem to be a way to retrieve the set of rows that match the filter.  This is useful when the user wants to invoke an action on the filtered set, for example export.

**Comment by Phillips126** [comment]
I found a way to perform this function, however, it may not be the best solution (I am fairly new to ReactJS).  What I was able to do is this...

Attach a "ref" to the Griddle component like such:
`<Griddle ref='Griddle' results={results} columnMetadata={columnMeta} ....  />`

Then, on a button onClick handler, I was able to perform:
`console.log(this.refs.Griddle.getCurrentResults())`

This would output the filtered results.
In my case, I collected the results to export as a CSV file.

On a side note, you can use this same strategy to use a custom Filter component and update the Griddle component with:
`this.refs.Griddle.setFilter("My Filter Text");`

**Comment by ryanlanciaux** [comment]
Thanks for posting this and sorry about the extreme delay in responding. This should be possible with the latest version of Griddle to get the set of filtered rows. Please see [the customization section](http://griddlegriddle.github.io/Griddle/docs/customization/) of the latest docs for more information on how this might be accomplished.

**Comment by sgedda** [comment]
I cannot see any example in the new docs of how to retrieve the filtered rows?

**Comment by sgedda** [comment]
I cannot see any example in the new docs of how to retrieve the filtered rows?

**Comment by KalalauEnterprises** [comment]
Really need this. Can anyone help with getting the filtered rows or filtered row count? Thanks!

**Comment by dahlbyk** [comment]
@KalalauEnterprises @sgedda I just posted an answer: https://stackoverflow.com/a/50121792/54249. I haven't tried the exact code, but it should be close. Probably the most important thing to note is the use of Griddle's `connect` function instead of the normal Redux one (see https://github.com/GriddleGriddle/Griddle/issues/647#issuecomment-340648281 if you need to connect your Griddle components to an external Redux store, too).

----------------------------------------

Assuming you're using `LocalPlugin`, you would use [`filteredDataSelector`](https://github.com/GriddleGriddle/Griddle/blob/a0df30779cf2fbbb2444e2faccf2b09b1018db55/src/plugins/local/selectors/localSelectors.js#L94-L114) in an enhancer/container to inject the prop into your presentation component. Roughly:

```javascript
import React, { Component } from 'react';
import Griddle, { connect } from 'griddle-react';
import PropTypes from 'prop-types';
import getContext from 'recompose/getContext';

const FilterContainerEnhancer = OriginalComponent => compose(
  getContext({
	selectors: PropTypes.object
  }),
  connect((state, props) => ({
	filteredData: props.selectors.filteredDataSelector(state)
  }))
)(props => <OriginalComponent {...props} />);

class FilterWithFilteredData extends Component {
  setFilter = (e) => this.props.setFilter(e.target.value);

  render() {
	return (
	  <div>
		<input
		  type="text"
		  name="filter"
		  placeholder={this.props.placeholder}
		  onChange={this.setFilter}
		  style={this.props.style}
		  className={this.props.className}
		  />
		({this.props.filteredData.length} rows)
	  </div>
	);
  }
}

// ...

return (
  <Griddle
	data={...}
	plugins={[LocalPlugin]}
	components={{
	  FilterContainerEnhancer,
	  Filter: FilterWithFilteredData
	}}
	/>
);
```

If you're not using `LocalPlugin`, you're on your own as `data` is expected to be managed externally.
