### ISSUE TITLE
Filtered View doesn't update

### ISSUE THREAD

**Issue by dmitrye** [GriddleGriddle/Griddle#220]
Steps to reproduce:
1. Create a Griddle data table with some data set. 
2. Add a record to the data set. Verify it's added.
3. Filter by name of the new record using default filter component. You should only see the new record in the filtered display.
4. Delete the newly created record from the data set.

Expected Behavior
- The filtered view should say "There is no data to display".

Actual Behavior
- The deleted record is still displayed, even though it's no longer in the data set.

Additional Info
- If you start changing the filter the view is updated and the deleted record is no longer visible.

**Comment by byteme980** [comment]
+1

**Comment by byteme980** [comment]
+1

**Comment by revokin** [comment]
Same here.  Using react dev tools I can see the <Griddle> 'results' prop updates but <GridTable> 'data' prop is not updating. I'm using Meteor 1.3 and React 15

**Comment by bommels** [comment]
+1

**Comment by ryanlanciaux** [comment]
Extremely sorry about the delay and thank you for the fantastic steps to reproduce. This has been fixed in version 1.0

Don't mind the really ugly styles here :)

## Initial State ##
![initial](https://cloud.githubusercontent.com/assets/85041/23288656/b316aec4-fa12-11e6-9750-f4a8b2f31bd1.png)

## Filtered ## 
![filtered](https://cloud.githubusercontent.com/assets/85041/23288664/bda1975a-fa12-11e6-8d12-f2f8aa2dc670.png)

## Removed Item ##
![removed](https://cloud.githubusercontent.com/assets/85041/23288676/d2d3b720-fa12-11e6-9151-2efc668e251e.png)

## Removed Filter ##
![unfiltered](https://cloud.githubusercontent.com/assets/85041/23288684/dbcd6d76-fa12-11e6-9d72-39990408488d.png)

Please let us know if there are any other issues! :+1:
