### ISSUE TITLE
Question: Is there a way to use sorting when using a customRowComponent?

### ISSUE THREAD

**Issue by McChen** [GriddleGriddle/Griddle#223]
I might be missing something, but I couldn't connect the dots between using a customRowComponent while preserving the original sorting capability. Header is also gone.

Any insights?

Thanks in advance.

**Comment by ryanlanciaux** [comment]
I realize it's been quite some time since you asked this but we recently release 1.0 which makes customization a lot more powerful. This is now possible with Griddle through overriding components rather than using a "customRowComponent" -- If this is still applicable for you please [take a look at the customization section on the docs](http://griddlegriddle.github.io/Griddle/docs/customization/) and let us know if that helps! :+1:

**Comment by kevinhughes27** [comment]
Congrats on 1.0! I'll have to check it out!

**Comment by ryanlanciaux** [comment]
Thanks! :)
