### ISSUE TITLE
there is a way to get the infinite scroll table to the 100% content height?

### ISSUE THREAD

**Issue by eriknyk** [GriddleGriddle/Griddle#224]
Hi, 
my questions is:
there is a way to get the infinite scroll table to the 100% content height?
just because actually it is being displayed with a static height 400px like in the example.

Best regards.

**Comment by legomind** [comment]
Not without a little extra work. In order to optimize rendering, Griddle must have a fixed height in order to calculate the number of rows to show in the list.

I wrap my component with [react-measue](https://www.npmjs.com/package/react-dimensions) and pass `this.props.componentHeight` to griddles `bodyHeight` prop.

**Comment by ryanlanciaux** [comment]
@legomind is correct -- Right now, we need a height to perform calculations on how the virtual scrolling should work. We have a plugin model in Griddle 1.0 and are trying to think of ways to make our virtual scrolling plugin more powerful and flexible. 

I'm going to close this for now but hopefully there will be some updates soon for this plugin :)

**Comment by sudhiryadav** [comment]
@legomind could you please share the code if you can as to how you implemented it in v 1.0?

**Comment by legomind** [comment]
@sudhiryadav yikes, this was like forever ago. I'll have to look in my backups and let you know.
