### ISSUE TITLE
Wrong paging

### ISSUE THREAD

**Issue by bazo** [GriddleGriddle/Griddle#233]
i have built a grid according to the example here http://griddlegriddle.github.io/Griddle/externalData.html

the problem is, when the state.currentPage = 0, then grid pager shows 1, when i click next i always get passed  page = 1 to setPage function, so the results stay the same and the page number never increases

however when the grid pager starts at page 2 the click on next always yields the next page number, which is correct

maybe it would help to not number pages internally from 0, since a grid can't have 0 pages

**Comment by tim-field** [comment]
Also seeing this :(

**Comment by ryanlanciaux** [comment]
I realize it's been some time since this issue has been opened but we have recently released 1.0 which is quite a bit different. This should be a bit better in the latest version. Please [see this page on a "Controlled Griddle" component](http://griddlegriddle.github.io/Griddle/examples/controlling-griddle/) for more info.
