### ISSUE TITLE
Fixed headers without infinite scrolling

### ISSUE THREAD

**Issue by aditigoel23** [GriddleGriddle/Griddle#248]
Hi - Is there a way to set up fixed headers without infinitescroll and with custom pager component? If not, is that on the roadmap?
thanks!

**Comment by adamgruber** [comment]
:+1:

**Comment by ryanlanciaux** [comment]
This is on the roadmap for 1.0 (or very shortly there after) :+1:

**Comment by aditigoel23** [comment]
Awesome! thanks!

**Comment by ruchigoyal2005** [comment]
@ryanlanciaux: Hi- is there any timeline for this feature? and when is the release date for 1.0? thanks !

**Comment by ryanlanciaux** [comment]
All -- thank you for the discussion here. I realize quite some time has gone on since we have made any updates but we are going a slightly different direction with Griddle 1.0 than we initially stated here. We are trying to _mostly_ keep the core functionality pretty slim and push other features, such as this, out as plugins. We are currently focusing on making the latest version of Griddle more solid but if anyone wants to try adding a plugin for this functionality, we'd love to see that 👍 

[The plugin documentation for Griddle 1.0 is available here.](http://griddlegriddle.github.io/Griddle/docs/plugins/)
