### ISSUE TITLE
Adding custom sorting for column

### ISSUE THREAD

**Issue by jintoppy** [GriddleGriddle/Griddle#250]
I dont see an option to set a custom sorter function to the column meta data? Is it possible? If not, is this in pipeline?

**Comment by ragebiswas** [comment]
+1 to this. It's a bit inconvenient to switch to external data loading just for custom sorting. Is it possible to hook into a method on click of the header row - that way I can at least reorder the data of griddle and force a re-render?

**Comment by ryanlanciaux** [comment]
Agreed - how we have it currently set up is not super flexible. 1.0 will allow this sort of behavior through plugins.

**Comment by ragebiswas** [comment]
Thanks @ryanlanciaux . Love the simplicity of griddle though, eagerly waiting for 1.0 :+1:

**Comment by ragebiswas** [comment]
One way in which I was able to workaround this problem - noting if it helps someone else. I added some meta information to the column text so that sorting by ascending/descending order works. I also added a custom formatter for that column so that I show just the stuff I want.

**Comment by ADanilychevJr** [comment]
@ragebiswas Could you elaborate more on how you did this? My Custom Components are not sorting correctly, instead they sort on another column when the header is clicked, for some reason.

**Comment by ragebiswas** [comment]
@ADanilychevJr Suppose you want to sort on column foo, but wish to modify the logic to something other than the default alphanumeric sort offered by griddle. What you have to do is:
1. use a custom renderer that shows the data that you want
2. map each value of your column to a "sortable" string/number. 

For example, if you want to sort by a field called status, where the values should be sorted as Open < Active < Closed. The default griddle sorting would give this order: Active < Closed < Open.

To fix this, map each status to an int value (open -> 1, active -> 2, closed -> 3). Use this as the column value in griddle, and for rendering use a custom renderer that renders the strings. Since griddle would sort on the values, you would get the correct sorting order.

**Comment by ADanilychevJr** [comment]
@ragebiswas Thanks so much! That was exactly the solution I was looking for. I didn't realize that columnName was what the table sorted on for custom Components (thought it was the plaintext in your custom render)

**Comment by ryanlanciaux** [comment]
Sorry about the delay on this one but we have released Griddle 1.0 -- custom sorting methods can be passed in on columnDefinitions now. Please see [customization documentation](http://griddlegriddle.github.io/Griddle/docs/customization/) and the [code here for supplying customSort](https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L119). Closing this one for now but please feel free to open a new issue if there are any problems :+1:

**Comment by harishmohanani** [comment]
@ryanlanciaux custom sort link is broken

**Comment by dahlbyk** [comment]
@harishmohanani [custom sort](https://github.com/GriddleGriddle/Griddle/blob/e8151462e43571300ff17d634688d2e06fa8b7cf/stories/index.tsx#L209-L261) link has been fixed.

GitHub tip: to turn any link into a permanent link (with SHA instead of branch/tag name), press <kbd>y</kbd>.

![image](https://user-images.githubusercontent.com/133987/31444063-b87bb8f2-ae60-11e7-9505-93e10ad78fad.png)
