### ISSUE TITLE
Scroll without iFrame

### ISSUE THREAD

**Issue by ACPK** [GriddleGriddle/Griddle#256]
How can I set infinite scroll to true without having an iFrame-like feature with two scroll bars?

**Comment by ankush86** [comment]
I need the same, I want infinite scroll on windows scroll instead of Iframe ( don't need to set bodyHeight). Please suggest me to do so.

Thanks in advance!

**Comment by ryanlanciaux** [comment]
This is something that will coming in 1.0. If someone wants to add to the current version as a PR we would take it but we've mostly been focusing on making 1.0.

**Comment by ankush86** [comment]
Thanks Ryan!

I will use 1.0 alpha version, can you please suggest the property Or Griddle code which I used to achieve infinite scroll on window scroll. Also my all data coming from external API's.

Thanks

**Comment by ankush86** [comment]
@ryanlanciaux Please reply to my last comment, I want that feature to integrate it in my app Or else please suggest me the changes I need to in package on my local.

Thanks

**Comment by ryanlanciaux** [comment]
Sorry about the delay on this! We have gone a slightly different route and are going with "virtual" scrolling in Griddle rather than the previous method where we kept appending rows to the table when scrolling. To enable this feature, `import Griddle, {plugins} from 'griddle-react'` and add position plugin to the Griddle plugins prop.

Modifying Griddle scrolling to use the page scrollbar instead of something specific to the table is a bit outside the scope of what we are adding to Griddle at this time but it could exist as a plugin that's made by the community. Please [see here for more info on creating plugins](http://griddlegriddle.github.io/Griddle/docs/customization/). :+1:
