### ISSUE TITLE
Hide "Rows Per Page" option in settings when using infinite scrolling

### ISSUE THREAD

**Issue by jjstrat3** [GriddleGriddle/Griddle#269]
Great react grid library!  My coworkers and I have been very impressed with the performance of infinite scrolling with our particular data-set!(1 million plus records that are paginated from the server)
What I was wondering if there's a way to remove certain options from the Settings component?  We feel like it doesn't make sense for the user to be able to toggle different pageSize values with the Setting's "Row Per Page" option when we're using infinite scrolling.  If there was a way to disable this or better yet define a custom settings component, that would be fantastic.

**Comment by jjstrat3** [comment]
*bump*  If I had a way to at least set a custom Settings component, then I could bypass this limitation.  This would be especially ideal for adding my own settings options and being able to better style the settings panel in general.

**Comment by qosmy-michael** [comment]
Same question - did you find a solution?

**Comment by qosmy-michael** [comment]
Not elegant - but if you remove "setPageSize, toggleCustom: from the last (return React.createElement) line in gridSettings.jsx you can kill it.

You may want to do additional tweaking.

return React.createElement('div', { className: 'griddle-settings', style: this.props.useGriddleStyles ? { backgroundColor: "#FFF", border: "1px solid #DDD", color: "#222", padding: "10px", marginBottom: "10px" } : null }, React.createElement('h6', null, this.props.settingsText), React.createElement('div', { className: 'griddle-columns', style: this.props.useGriddleStyles ? { clear: "both", display: "table", width: "100%", borderBottom: "1px solid #EDEDED", marginBottom: "10px" } : null }, nodes));

**Comment by shraddhacse** [comment]
+1. Settings is a great feature, but need a way to hide/remove Rows per page as I don't need to use Griddle pagination.

**Comment by ryanlanciaux** [comment]
I realize that quite some time has gone on since this issue but we have recently released Griddle 1.0 and have taken this specific issue into account when designing the new features. Griddle settings are now a bit more composable and [Griddle plugins](http://griddlegriddle.github.io/Griddle/docs/plugins/) can specify what shows up in settings ([more info about the new settings architecture -- code](https://github.com/GriddleGriddle/Griddle/tree/master/src/settingsComponentObjects)). 

For now, a plugin could be specified to turn this off, however, we're currently adding features to make this so standard customization options could enable / disable settings components. 

Closing this one for now but please feel free to open a new issue if any problems are encountered. :+1:
