### ISSUE TITLE
How to show empty grid when results are empty?

### ISSUE THREAD

**Issue by mikestopcontinues** [GriddleGriddle/Griddle#274]
There doesn't seem to be a way to show an empty grid when results is an empty array. Is there a way to do so?

**Comment by tingwei628** [comment]
hi @mikestopcontinues 
My friend, Mr.Sung, also found this problem ,too
In griddle.jsx, #733  it should improve like this
shouldShowNoDataSection: function(results){
    return false;  // it should keep grid when no data's in the grid
 },
thanks

**Comment by mikestopcontinues** [comment]
Thanks, @tingwei628. I had found those lines. I really want a canonical way to do it that doesn't require forking.

**Comment by ryanlanciaux** [comment]
If someone wants to add a PR that fixes this, that would be much appreciated.

**Comment by mikestopcontinues** [comment]
I'm very excited for Griddle 1.0. I think going forward, there should be no such no-data feature, as a user can easily render or not render Griddle from outside the component. That said, the PR just adds a prop to "allowEmptyGrid".

**Comment by jsdmc** [comment]
Hello there!
@ryanlanciaux I've added fix in this PR https://github.com/GriddleGriddle/Griddle/pull/312
Also changed the way how uniquie keys is assigned to rows. Before I got error https://github.com/facebook/react/issues/2410 that was caused because react was not able to find unmounted rows (with new keys each time)

**Comment by joellanciaux** [comment]
Hey @jsdmc - everything should be merged in. Thanks for making the update :+1:
