### ISSUE TITLE
Question: Responsive setup

### ISSUE THREAD

**Issue by reintroducing** [GriddleGriddle/Griddle#278]
I've tried searching Google and this repo but have not found a definitive way to use Griddle with responsive functionality.  I really apologize if I'm missing something but is there an example somewhere that shows Griddle being used in a responsive setup and how columns would collapse/look when on smaller breakpoints?  Or is this left entirely to the developer to take care of separately from Griddle functionality?

I appreciate any help offered.

**Comment by ryanlanciaux** [comment]
Thanks for the question! This is one of the areas where we were trying to avoid giving a definite concrete approach and leave it up to the developer.

If it were me, however, I would probably wrap Griddle in a container that was aware of responsive breakpoints (maybe something like [react-responsive](https://github.com/contra/react-responsive)) and pass different columns into the array depending on size. Also beyond a certain point, I would probably pass in a custom component for the list elements to display the data as cards rather than a table. 

When we release version 1.0 I would love to see this sort of functionality as an optional plugin. It seems like something many could benefit from but we don't want to necessarily ship that out of the box.

I hope that helps and please feel free to follow-up with any additional questions or thoughts around this!

**Comment by reintroducing** [comment]
@ryanlanciaux Thanks a ton for the great answer. This is kind of what I imagined so it's great confirmation.  I'd love it if a plugin was available for this in the 1.0 release as I was just looking at that roadmap but I know that will take some time and someone to step up to do it. In any case, keep up the great work.
