### ISSUE TITLE
Allow setting "available" columns

### ISSUE THREAD

**Issue by tad9ab** [GriddleGriddle/Griddle#285]
Our responses do not always return all of the possible columns (due to those values being null, and the server sending nothing instead of null values).  However, if we want our column settings to stay the same across multiple queries, it would be nice to be able to specify the "available" columns so that it will use that list instead of the properties of the JSON response object.

For example, the super set of all columns is A, B and C.  However, a response returns 2 rows that just have fields A and C.  I want to be able to show A, B and C in the properties section to select columns.

If this is already possible, please elaborate.

**Comment by ryanlanciaux** [comment]
I realize this issue is from some time ago but we have recently released Griddle 1.0 that makes this a bit clearer. Now the columns you want to display can be provided via a `<ColumnDefinition />` component whether or not the column has data. Please [see here in the docs](http://griddlegriddle.github.io/Griddle/docs/) for more information on this. :+1:
