### ISSUE TITLE
Does customRowComponent support <tr> <td>

### ISSUE THREAD

**Issue by tungwaiyip** [GriddleGriddle/Griddle#289]
When I turn on `useCustomRowComponent`, I find that the table is rendered very differently. Normally it is a HTML &lt;table>. If I turn on `useCustomRowComponent`, it becomes just nested div. In fact it strip away any &lt;tr>, &lt;td> that my class renders. I have a render function that return a list of &lt;td> inside a &lt;tr>. What is wrong with that? Why does Griddle produce a table?

**Comment by legomind** [comment]
You would need to pass in a custom grid component that handles rendering the table body to accomplish that.

**Comment by ryanlanciaux** [comment]
Sorry about this confusion! It's poor naming on our part. Can you try using `useCustomTableRow` and `customTableRow` instead and see if that is better? We should have called customRow something else earlier on as it's a repeated div rather than a table row (which is really helpful in some scenarios -- but not this one :smile:). We've tried to make this a lot clearer in the customization in 1.0 ..

1.0 adds a lot more customization, in general -- these docs are not quite ready yet but [a list of the components that can be overrode is available here](https://github.com/GriddleGriddle/griddle-docs/blob/master/pages/docs/customization/_exampleSummary.md#default-component-modules)

**Comment by abologna-r7** [comment]
useCustomTableRow is not a thing yet :/

**Comment by ryanlanciaux** [comment]
Griddle 1.0 has been released along with the customization options mentioned. Please [see the customization documentation](http://griddlegriddle.github.io/Griddle/docs/customization/) for more info :)

[An example of this customization in use is available here](http://griddlegriddle.github.io/Griddle/examples/asList/). Closing this for now but please feel free to open a new issue if any problems are encountered :+1:
