### ISSUE TITLE
react-tab index rest on a click event

### ISSUE THREAD

**Issue by aaronucsd** [GriddleGriddle/Griddle#315]
Hi. I have an onclick event fire from one of my tabs, but on fire, it somehow reset the tab index to go back to the first tab. Say i have  2 tabs, and i'm on the second page of the tab 2, which has Griddle table, when i click on something in one of the griddle's table column it triggers the react tab to go back to the first tab vs staying put. Any ideas?

```
const LinkComponent = ({ data, rowData }) => {
  let result = <span></span>;
  if (data) {
    result = (
      <div>
        <span>{rowData.user}</span>&nbsp;
        <span onClick={this.props.onClickUserDetails.bind(this, rowData.user)}>
          <i className='fa fa-info-circle fa-lg'></i>
        </span>
      </div>
    );
  }
  return result;
};
const columnMeta = [
  {
    columnName: 'user',
    order: 1,
    locked: false,
    visible: true,
    customComponent: LinkComponent,
    displayName: 'User ID',
  },
```

**Comment by ryanlanciaux** [comment]
I'm sorry about the delay -- I'm really not sure what would be causing this and am a bit hesitant to say it's something in Griddle (it very well could be) with the interaction with another component going on here. I realize it's been some time since this issue was opened and we've released Griddle 1.0 since then.

I'm going to close this one for now but please feel free to open a new issue if you're still having trouble after this 1.0 release. :+1:
