### ISSUE TITLE
Use Lodash Instead of Underscore

### ISSUE THREAD

**Issue by blkmutt** [GriddleGriddle/Griddle#322]
Just use necessary modules from lodash instead of including underscore. See this issue for details.
https://github.com/meteor/react-packages/issues/168

**Comment by ryanlanciaux** [comment]
Yea we should do this :+1: We will need to include just the methods from lodash that we want to use just like we are in 1.0. 

If anyone wants to take a stab at this that'd be good -- Otherwise, I'll try to get to it soon. Basically we want to do something like this:

```
var debounce = require(lodash.debounce);
```

Anywhere that we were using `_.debounce` it should use the newly imported module instead (I don't think we're using debounce here but just an example :smiley:).

I think we should bump the version to 0.4.0 after this also.

**Comment by yorchv** [comment]
I will do this change. Seems great.

**Comment by ryanlanciaux** [comment]
Thank you! That would be awesome! :+1:

**Comment by yorchv** [comment]
@ryanlanciaux I have been able to update the package successfully, the only problem is about the documentation. Should we make the lodash modules as dependencies instead of peerDeps? This removes the need to have underscore installed or available.

**Comment by ryanlanciaux** [comment]
Awesome news! I think it's fine to make them actual dependencies and remove underscore entirely :+1:

**Comment by yorchv** [comment]
Check https://github.com/GriddleGriddle/Griddle/pull/325

**Comment by ryanlanciaux** [comment]
Thanks so much -- I'll try to get that merged in the next day or so here and publish this out.

**Comment by yorchv** [comment]
plans on merging this?

**Comment by ryanlanciaux** [comment]
Yes -- sorry about the delay. I was going to try to rebase it on top of master but if you want to do that also that would be good -- it's finding conflicts (which is odd because I don't think we merged anything between start and finish of this task)

Thanks a ton for checking in on this -- it's an awesome thing and def. something that should be merged in.

**Comment by yorchv** [comment]
Done

**Comment by ryanlanciaux** [comment]
This is in 0.4.0 - thanks again @yorchv and sorry about the delay in making it a released version!
