### ISSUE TITLE
onclick on row triggers event if I want to open a subgrid

### ISSUE THREAD

**Issue by orangecoding** [GriddleGriddle/Griddle#324]
Hey,

I've start using subgrids which is nice. Well it would be much more awesome if I could add my own columns to parent and children, but I've seen that this is planed. (Is it planed for 1.0?)

Anyways, If I hook a onClick on a row, it also triggers if I try to open the subgrid. Then the subgrid won't open.

**Comment by amrut-bawane** [comment]
Facing a similar issue. Did you find anything to resolve this?

**Comment by orangecoding** [comment]
No. obviously the creators of Griddle don't care about this..

**Comment by ryanlanciaux** [comment]
Sorry that you're encountering a bug in Griddle and that we've been a bit delayed in getting to this. We are spending a lot of our free-time working on 1.0 which takes care of this issue.

In the meantime, if this is something that's really tripping you up, we would love a PR that resolves. :+1:

**Comment by ryanlanciaux** [comment]
We've recently released Griddle 1.0 which takes more of a plugin model approach to features such as subgrid rather than shipping with a lot of these features in the core module. Subgrids will be coming as a plugin at some point (or if someone wants to take it on -- this would need to be updated from the alpha style plugins to current, release plugins). 

Closing this one for now (since sub grid is not really part of this repo anymore) but when the official 1.0 plugin is released it should no longer fire off the onclick for row when expanding a subgrid.
