### ISSUE TITLE
Where to set rowData prop?

### ISSUE THREAD

**Issue by DinoJay** [GriddleGriddle/Griddle#37]
Sorry Guys to bother you again. 
In my project, I would like to make extra data available to the custom component of the grid. So, I was trying to make use of the new rowData prop.
But unfortunately I have no clue where to set it. I tried to put it in < Griddle />, but no success.
Could you help me out another time?
Many thanks in advance!

Best Regards
Jan

**Comment by ohana54** [comment]
Hi,
I'm trying to achieve a similar thing in order to support cell selection, but it looks like I can't use a callback from my custom cell component so the grid will maintain the selected state. I'm using the latest version.

Is what I'm trying to achieve possible today? Did I miss something?

Thanks!

**Comment by ryanlanciaux** [comment]
Simple row selection is currently available in Griddle, however, we are working on rewriting a bit of the component to make this a bit more robust. I've opened the issue over on the new(ish), griddle-render project instead of here https://github.com/GriddleGriddle/griddle-render/issues/14.
