### ISSUE TITLE
Version 0.5.0 `npm install` issue with missing `modules` directory

### ISSUE THREAD

**Issue by hwillson** [GriddleGriddle/Griddle#388]
Hi guys - thanks for pushing the 0.5.0 changes up! One thing I just noticed - `package.json` has the following:
```
  ...
  "main": "modules/griddle.jsx.js",
  ...
```
It looks like the modules directory and contents don't exist in `node_modules/griddle-react` after a fresh `npm install`. I can create them by triggering a build myself, but they aren't included by default. Since `modules/griddle.jsx.js` is listed as the `package.json` module ID, this will likely cause problems. Is this intentional?

Thanks again!

**Comment by ryanlanciaux** [comment]
Hey @hwillson! Thanks for posting this and so sorry you encountering any issues with this! That would not be intentional and I am a little confused as to why that modules directory didn't make it (I will have to look through our build process and make sure nothing is missing).

0.5.1 is available and  seems to include the modules directory upon clearing griddle-react from npm cache and fresh install. Please let me know if you are still encountering anything with this version.

**Comment by hwillson** [comment]
Awesome @ryanlanciaux - 0.5.1 did the trick (`modules` directory is showing up properly). Thanks!

**Comment by ryanlanciaux** [comment]
Awesome - glad that took care of it :+1:
