### ISSUE TITLE
Action buttons in separate column

### ISSUE THREAD

**Issue by firen** [GriddleGriddle/Griddle#394]
Hi,
My data json looks like that:

``` javascript
var data = {
  id: "<value>",
  comment: "<value>"
}
```

And my metadata is:

``` javascript
var columnMeta = [
    {
        "columnName": "id",
        "order": 1,
        "locked": false,
        "visible": true
    },
    {
        "columnName": "comment",
        order: 2
    },
    {
        "columnName": "actions",
        "customComponent": LinkComponent
    }
];
```

When I try to render Griddle I get empty 'actions' column. It looks like Griddle ignores column rendering when no json data is provided. I have moved LinkComponent to 'comment' column and it renders correctly.

Can you please confirm if that is expected behaviour? If yes how can I add action buttons like 'edit' or 'delete' next to each row?

Regards,

**Comment by yarulan** [comment]
Same thing. I ended up adding dummy field to my data.

**Comment by mwtorkowski** [comment]
Yeah, same here. It would be cool to be able use children to pass columns definition instead of relying on columnMeta prop. E.g.

    <Griddle ..>
        <GriddleColumn displayName="Foo" columnName="id" customComponent={SomeCustomComp}/>
        <GriddleColumn displayName="Actions">
            Anything I want in here... <Link to={...} />
        </GriddleColumn
    </Griddle>

**Comment by ryanlanciaux** [comment]
Thanks for the ideas here! In 1.0 we are using ColumnDefinition components to define what columns are available rather than the metadata for this very scenario. Still churning on a couple things in the API (so trying to get that straightened out before officially releasing / pushing to beta) but it's working well on some projects where I'm using it.

The use is similar to what you described.Kind of like this

```
<Griddle data={someData}>
  <RowDefinition {...someGlobalSettingsForRows}>
    <ColumnDefinition id="id" customComponent={SomeCustomComponent} />
    <ColumnDefinition id="somethingThatDoesntExistInData" customComponent={OtherCustomComponent} />
  </RowDefinition>
</Griddle>
```

The cell data will be related to whatever is in the data for the given ID, however, we can add columnDefinitions to the grid that don't have corresponding data and work against the entire row's data instead. We can then make use of the rowData in the custom component as follows:

```
const OtherCustomComponent = ({originalRowData}) => (
  <div>
    <button type="button">{originalRowData.title}</button>
  </div>);
```

This is all working well for me but trying to solidify the final API for state management a bit since there could be community plugins based on that and I would prefer to get it to a point that I'm totally sold on before an official release (don't want to get this released and say "okay update your plugin to use this new format for state management since I decided I wasn't too happy with ____"). :)

**Comment by slashwhatever** [comment]
+1

**Comment by juampick** [comment]
+1

**Comment by jariwalabhavesh** [comment]
+1

**Comment by emorling** [comment]
@firen @yarulan @mwtorkowski how have you solved Editing cells in Griddle? Thanks

**Comment by ryanlanciaux** [comment]
All [the above comment](https://github.com/GriddleGriddle/Griddle/issues/394#issuecomment-228097655) is how I would recommend approaching this with Griddle 1.0. The gist of it is a ColumnDefinition would be created that doesn't correspond to a property in the data for the row but would be provided a custom component that has the actions. The actions would either interact with Griddle's state or interact with the data (either locally or on the server). 

Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍

**Comment by bpugh** [comment]
Thanks @ryanlanciaux, your comment is exactly the solution I was looking for but it doesn't look like this is currently implemented as `value` and `griddleKey` are the only props passed to `customComponent`. I poked around in the code and I believe I could add it with minimal effort.
Would you be open to me submitting a PR for this?

**Comment by ryanlanciaux** [comment]
@bpugh - I really appreciate this. Are you suggesting the whole rowData as well for customComponents? I think we should have an "enhancer" utility for providing row data to custom components. 

Something like we're doing here https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L67 -- the thought right now is we mostly are only giving the components the bare minimum of what they need and letting them connect to get more so it's opt-in to more data instead of coming up with beefier `shouldComponentUpdate`s 

If you had time and we're talking about the same thing, it would be awesome to make something under utils like dataUtils or something (I'm bad at naming things) that has enhanceWithRowData on it.

Custom components could then import enhanceWithRowData and then 

```
  import { enhanceWithRowData } from 'griddle-react';

  class SomeCustomComponent extends React.Component {
    ...
  }

  const CustomComponentWithRowData = enhance(SomeCustomComponent);
  ...
  <Griddle data={data}>
    <RowDefinition>
      <ColumnDefinition id="name" customComponent={CustomComponentWithRowData} />
    </RowDefinition>
  </Griddle>
```

Any thoughts on this?

**Comment by Mastergalen** [comment]
For those arriving from Google:

Solution is in the docs: http://griddlegriddle.github.io/Griddle/examples/getDataFromRowIntoCell/

**Comment by dahlbyk** [comment]
Additional reading: https://github.com/GriddleGriddle/Griddle/issues/623#issuecomment-290721423
