### ISSUE TITLE
Changing columnMetadata prop has no effect

### ISSUE THREAD

**Issue by gidili** [GriddleGriddle/Griddle#407]
I am on 0.3 and I am not sure if this is by design or not or if it got fixed in later versions, but here's what I am experiencing.

I am generating columnMetadata based on what I need to display, and if I render with a given value for columnMetadata but then add a column in to columnMetadata and trigger a re-render from my parent component passing down the updated prop this has no effect on the grid.  

As in, the raw data shows in the new column but the metadata for the new column (e.g. customComponent, displayName) does not get picked up.

It's almost as columnMetadata is not part of the griddle state, so changes are disregarded once griddle renders once. Looking at the source seems to confirm this. 

Any ways around this or pointers if I wanted to extend griddle so that changes to columnMetadata would be picked up by a griddle render?

Thanks!

**Comment by gidili** [comment]
Possibly related? https://github.com/GriddleGriddle/Griddle/issues/391

**Comment by jonifen** [comment]
I've also encountered this in version 0.3.1.
I was able to work around it by including everything in the columnMetadata, and then change the columns array to toggle the column visibility at runtime.
This may not help if you're changing the customComponent for a column in the metadata or something like that though.

**Comment by gidili** [comment]
@jonifen thanks - glad to hear it's not just me and thanks for sharing your work-around :) 

Yes, that's exactly what I am doing, I am building a generic grid component on top of griddle that my app is going to reuse in a variety of scenarios so as a requirement I need to be able to change columns completely, including custom components. 

I am basically unmounting and re-mounting griddle when that happens as a workaround.... not optimal but works for now.

**Comment by daveashworth** [comment]
is #406 what you're talking about? It looks like this _is_ fixed in later versions, but if you can't upgrade for some reason, one workaround is adding a `key={somekey}` property to the Griddle component that changes when you update your `columnMetadata`. This will force Griddle to reload the `columnMetadata` and re-render correctly. Not ideal, but it works...

**Comment by gidili** [comment]
@daveashworth yes that's exactly it. I will try to upgrade to 0.5 and hope there's not too many breaking changes. 

Just in case, do you mean set `key={somekey}` when rendering and then reach into the DOM and manually change the value of that attribute when my column metadata gets updated to force a full re-render? 

Thanks for the tip!

**Comment by daveashworth** [comment]
Well, for example I had something like this:
```
<Griddle
      columns={columnMeta.map((c) => c.columnName)}
      columnMetadata={columnMeta}
      key={outerGroupBy.length}
      results={groupedLeadsCollection}
    />
```
where that `outerGroupBy` was being passed into the component as a prop. That worked in my case just due to the data we were grouping by, but any key that changes whenever you need the Griddle component to re-render should work. Make sense? But yeah, hopefully you can just upgrade to `0.5.1` and be good!

**Comment by modomodo** [comment]
This problem stills persists with Griddle v0.5.1

**Comment by daveashworth** [comment]
This is fixed in the current codebase: https://github.com/GriddleGriddle/Griddle/blob/master/scripts/griddle.jsx#L368
I was under the assumption that codebase existed in the current release, but it doesn't... 
When are the current changes going to be released to npm?

**Comment by daveashworth** [comment]
Just FYI, after yesterday's commit adding the build... it works to add this to your package.json file and install griddle from github at that commit vs from npm (until a newer version of griddle is published).

`"griddle-react": "https://github.com/GriddleGriddle/Griddle/tarball/07542a565d7f7f4f84ae5a95da5d466f57933292"`

**Comment by DmitryAuine** [comment]
@daveashworth Hey! Thx for fixing this bug, but after update to 0.6.0 the triangle that responds on sorting is not showing! 
Here is the video: https://monosnap.com/file/URAPMI8G3ARcvQLYlJ38ycCL78GFcO

**Comment by daveashworth** [comment]
Hi @DmitryAuine, I'm not the author (or a contributor to Griddle) of any of the bug fixes here, just commenting on how you could get your hands on the 0.6.0 version before they released it the other day.

I'd create another issue pointing out the problem you're experiencing. But it looks like this current issue can be closed now since the release of 0.6.0 to npm.

**Comment by ryanlanciaux** [comment]
Thanks - @daveashworth.

@gidili -- if you get the chance to confirm that this is looking good, we would appreciate getting it closed :+1:

@DmitryAuine Sorry that you're encountering some problems with sorting -- if you could open a new issue with what you're seeing, that would be great!

**Comment by gidili** [comment]
@ryanlanciaux @daveashworth yes - all good for me now! 👍
