### ISSUE TITLE
Is there a way to show row "detail-view" ?

### ISSUE THREAD

**Issue by adobeflex1** [GriddleGriddle/Griddle#437]
I want to get the functionality of, when i click on a row, it should expand and display some detail information (detail view) just below that clicked row.

Is there a way to get that functionality?

**Comment by ryanlanciaux** [comment]
That sounds like cool functionality and unfortunately, it's not built in to Griddle. In a future version it will be possible to override the table row (this is a bit different than the custom row component) to where this functionality could be added.

I'm closing this for now because it's something that is on the roadmap. Thanks!
