### ISSUE TITLE
initialSortAscending doesn't seem to work anymore

### ISSUE THREAD

**Issue by orangecoding** [GriddleGriddle/Griddle#445]
Hey.

Hopefully it is not just me, but it seems the field initialSortAscending doesn't work anymore. It previously took care of the sorting direction. Now it doesn't have any effect anymore. Either I switch it to true or false, it still sorts it asc... This problem appears in Griddle 0.6.0. In 0.5.1 it works correctly.
I've now switched back to v 0.5.1..

**Comment by ryanlanciaux** [comment]
Thanks for letting us know and sorry about that. We'll look into this.

**Comment by jonifen** [comment]
I'm also encountering this issue with the latest version after upgrading following the fix for #391 
It looks like the initialSortAscending property has been removed from the code entirely? Is there an alternative way to handle the initial sort order in the newer versions that isn't in the documentation?

**Comment by harrisgeo** [comment]
Experiencing the same problem here. Solved it by switching back to version 0.3.0 I was using before updating to 0.6.0

**Comment by KushnirAndrew** [comment]
Hey,
According to Griddle v0.6.0 code, the `initialSortAscending` parameter was removed and you can use `columnMetadata.sortDirectionCycle` instead to define the initial sorting order (first element in an array) as well as the order in which the column order should be changed in case a user clicks on a column header. Note: you still need to use `initialSort` Griddle prop to define which column should be used to sort data by default.

**Comment by ryanlanciaux** [comment]
Thanks for calling this out -- would it be helpful if a property was added that set the new property when someone was using the previous property (and toss a debug note to console saying that it's going away in future)? Would it be better to keep things as they are currently?

**Comment by KushnirAndrew** [comment]
Thanks for the reply @ryanlanciaux! There is a couple things that might be helpful:

1. I think it'd be great to update Griddle documentation: add information about `sortDirectionCycle` into regular docs (it's currently mentioned in release notes only afaik) and remove `initialSortAscending ` prop (or mark it as deprecated since v0.5 and add a reference to the newly added `sortDirectionCycle` option).
2. What you've proposed would also be great (keeping backwards compatibility for some time and add warning into a console with the necessary instructions/links on how to transition to the new configuration), since more users might be confused after upgrading Griddle to v0.6.

I'm also wondering if it's possible to keep the `initialSortAscending` option? Having an ability to define individual sorting cycles for different columns gives a great flexibility, but requires more configuration for a user. I'd vote for keeping both options and translate `initialSortAscending` prop into more flexible `sortDirectionCycle` one under the hood (if it's not explicitly specified by a user).

**Comment by jonifen** [comment]
Well don't I feel daft for not reading the release notes!
Thanks @KushnirAndrew for spotting this out. I've tried the sortDirectionCycle parameter in the columnMetadata in my test project and it works a dream - I set it to ['desc', 'asc'] to get initial sort as descending and vice-versa.

Having a one-place initial sort setting is useful, especially as you're already setting the column to sort on with 'initialSort'. But, the sortDirectionCycle parameter is more powerful and I'd guess it only needs to be changed from the default on the initial sort column anyway?

**Comment by ryanlanciaux** [comment]
Thanks for the discussion here! We've released Griddle 1.0 and the ability to set an initial sort is present but the way to achieve this is slightly different. Please see http://griddlegriddle.github.io/Griddle/examples/defaultSort/ for more information.

I'm going to leave this open as we're still planning to release 0.x for a while as we solidify the upgrade path a bit more. That said, [I still would love some help maintaining 0.x](https://github.com/GriddleGriddle/Griddle/issues/429)
