### ISSUE TITLE
Sorting direction icon doesn't show up when useExternal is set

### ISSUE THREAD

**Issue by kevinmuller1220** [GriddleGriddle/Griddle#457]
Using Griddle, I'm loading data externally by setting useExternal to true, and I found that it doesn't render the sorting direction icon when header cell is clicked for sorting.
The data sorting works with externalChangeSort but the icon doesn't just show up.

I found some related code on line 80 in /modules/gridTitle.jsx.js
```
if (that.props.sortSettings.sortColumn == col && that.props.sortSettings.sortDirection === 'asc') {
                columnSort = that.props.sortSettings.sortAscendingClassName;

```
Here the sortDirection is always null when useExternal is set to true.

And inside changeSort function in /modules/griddle.jsx.js, it won't set state of sortDirection simply returning when useExternal is set.
```
if (this.props.useExternal) {
    this.props.externalChangeSort(column, this.props.externalSortColumn === column ? !this.props.externalSortAscending : true);
    return;
}
```
Looking forward to have a quick fix on this.

**Comment by BrandKNY** [comment]
@kevinmuller1220 I was suffering from the same issue as well. Clearly the Griddle library should be implemented to work with the sort icon features working whether it be a documented external implementation provided by users or through existing default internal implementation. However, my workaround for now was to implement a custom SortableHeaderComponent class (I'm using material-ui svg icons):

    export default class SortableHeaderComponent extends Component {
      constructor(props) {
        super(props);
      }

      textOnClick(e) { }

      render() {
        return (
          <span onClick={::this.textOnClick} >
            <div><strong style={this.props.style}>{this.props.displayName}</strong>{this.renderSortArrow()}</div>
          </span>
        )
      }

      renderSortArrow(){
        if(this.props.state.sortAscending) {
          return ( <SortAscendingArrow /> );
        }
        return ( <SortDescendingArrow /> );
      }

I use containers to basically manage all of the state and props data for components, so in that wrapper container is where I set and pass in the `columnMetadata` object array to my component class implementing Griddle. When I build my columnMetadata objects I add the CustomHeaderComponent: 

    getColumnMetadata() {
        return (this._getCurrentProjectedFields(this.state)).map((f, i) => {
          return {
            "columnName": `${f.id}`,
            "order": i,
            
            ...

            "sortable": true,
            "displayName": `${f.label}`,
            "customHeaderComponent": SortableHeaderComponent,
            "customHeaderComponentProps": {
               style: { color: 'black'},
               state: {
               sort: this.state.sort,
               sortColumn: this.state.sortColumn,
               sortAscending: this.state.sortAscending
            }
         }
      }
    }

The important part of this is that I keep track of the column being used to sort-by currently and the direction, and update this whenever my externalChangeSort function is triggered, so that it is correctly passed on to the custom header component where the logic determines which direction arrow should be rendered, if any.

**Comment by adamboduch** [comment]
@BrandKNY nice. I had no luck myself trying to fix it with custom header components. I'll try this. Hopefully this fix makes it's way into Griddle soon.

**Comment by ryanlanciaux** [comment]
Could someone please make a PR for this functionality in the 0.x version. When 1.0 is done it should work out of the box but trying to finalize the API so we're not saying "here's 1.0 ... nevermind here's 2.0 with a better API" a month or two later :)

**Comment by DmitryAuine** [comment]
Please do something :)

**Comment by M3lkior** [comment]
Same issue here ...

**Comment by tatethurston** [comment]
Fixed [486](https://github.com/GriddleGriddle/Griddle/pull/486)
