### ISSUE TITLE
Row metadata never changes unless a key is specified

### ISSUE THREAD

**Issue by ericsvendsen** [GriddleGriddle/Griddle#552]
`rowMetadata` is evaluated every time a `dispatch` is fired from my `onRowClick` event, however as far as `rowMetadata` is concerned, the global state is permanently stuck in its initial state.  So even though I've saved the clicked row data as an object on the global state, when `rowMetadata` is re-evaluated it can't see the updated state.

While googling, I came upon issue #352 and when I specified a `key` property as suggested at the bottom of that thread, `rowMetadata` magically started updating.  I get the feeling that this is not expected since it's not documented anywhere, and even in #352's thread it's mentioned as a band-aid.

In the code below, `stateProps` is what would never be updated.

```
rowMetadata: {
    bodyCssClassName: (rowData) => {
        console.log(stateProps);
        return rowData.requirementId === stateProps.report.requirementId ? 'standard-row selected' : 'standard-row';
    }
}
```

But if I add the `key` property, then everything is fine:

```
<Griddle 
    ...
    rowMetadata={props.rowMetadata}
    key={props.report.requirementId}/>
```

I feel like this is something that's hard to explain, so if I'm doing as bad a job of it as I think I am I can try to provide a working example.

**Comment by ryanlanciaux** [comment]
Ahh -- yea. We experienced this when moving stuff to 1.0 also and it _should_ be fixed there but it's not quite ready. I realize that doesn't help in this situation -- I've been trying to get some more folks working on the current stuff because that'll still be around for awhile after 1.0 is released. I will try to look into this but a lot of my time has been going to 1.0 as it fixes a number of issues all at once.

**Comment by Cerberus** [comment]
I will make a PR to resolve this issue.
