### ISSUE TITLE
can't use same id twice in columndefintion

### ISSUE THREAD

**Issue by macrozone** [GriddleGriddle/Griddle#609]
## Griddle version

v1.1.0

## Expected Behavior

I can add multiple `<ColumnDefinition />` with the same id, so that i can
have multiple columns accessing the same value

## Actual Behavior

Only the last columndefinition is visible

## Steps to reproduce

add two columnDefinition with same id

**Comment by dahlbyk** [comment]
I can't speak for the maintainers, but reusing `id` seems undesirable since that is how columns are uniquely identified. See https://github.com/GriddleGriddle/Griddle/issues/623 for how to reference data from other columns in a custom component.

**Comment by ryanlanciaux** [comment]
We were not intending for this sort of behavior. It's definitely possible I'm being short-sighted but can you please explain where this would be necessary? Maybe I can be convinced otherwise :D If not maybe there's another way to solve what you're trying to do -- I'd love to help either way. Thanks!
