### ISSUE TITLE
Sort columns using a dropdown select [Griddle v1.3.1]

### ISSUE THREAD

**Issue by sstauross** [GriddleGriddle/Griddle#670]
Hello, i am trying to achieve sorting in a variety of ways using a dropdown select with the following options for example:
- Date
- Price [asc]
- Price [desc]

How can i connect the selected way of sorting with the column sorting and remove the arrows next to the column headings? Thanks in advance!

**Comment by jackgeek** [comment]
I have tried to do this also.  My implementation works by calling the onSort event, which I have because I implemented [external control](http://griddlegriddle.github.io/Griddle/examples/controlling-griddle/).  However when I am using the Local plugin I do not use my onSort implementation.  I have no idea how to get my custom Sort component to work with the Local plugin.

**Comment by jackgeek** [comment]
I just figured it out.  If I am using the local plugin I dispatch a GRIDDLE_SET_SORT action.

```
import { actions } from 'griddle-react';
const { setSortColumn } = actions;
...
function mapGriddleDispatchToProps(dispatch) {
  return {
    setSortColumn: (sortProperties) => dispatch(setSortColumn(sortProperties))
  };
}

```
The sortProperties looks like this:

```
{
  id: 'myColumn',
  sortAscending: true
}

```
