### ISSUE TITLE
OnGetPage Event not working

### ISSUE THREAD

**Issue by aftabnaveed** [GriddleGriddle/Griddle#672]
## onGetPage event not getting triggered

I have my own wrapper for Griddle component. The reason for having a wrapper is to apply styles and common events across all my grids in the application (Not sure if this is a best practice). Everything seems to be working fine, but my onGetPage handler is not working. Below is the code. 

```javascript
class SkuRuleGrid extends React.Component {

	_onNext = () => {
		console.log('Next button clicked...');
	}

	_onPrevious = () => {
		console.log('Previous button clicked....');
	}

	_onGetPage = (pageNumber) => {
		console.log('Get Page...');
	}

	render() {
		
		return(
			<Box title="Sku Promotion">
				<Grid 
					data={data} 
					plugins={[plugins.LocalPlugin]} 
					
					events={{
						onNext: this._onNext,
						onPrevious: this._onPrevious,
						onGetPage: this._onGetPage {/*This is not working*/}
					}}
				/>
			</Box>	
		);
	}
}

```

**Comment by aftabnaveed** [comment]
Removing plugins={[plugins.LocalPlugin]}  fixed the issue. My bad.

**Comment by dahlbyk** [comment]
I'm pretty sure this is a bug in [`LocalPlugin`'s `PageDropdownContainer`](https://github.com/GriddleGriddle/Griddle/blob/2988f42dd4b3db027587694028783f6507e7848d/src/plugins/local/components/PageDropdownContainer.js): it grabs `setPage` directly from `actions` instead of from `events` like the [default `PageDropdownContainer`](https://github.com/GriddleGriddle/Griddle/blob/794064ed95d2a45dbff45533f0eb7dc00879076b/src/components/PageDropdownContainer.js#L19).

**Comment by RemiBonnet** [comment]
Hello, 

Did you have an idea to fix that ? I have the same problem but I need to use LocalPlugin.

Thanks !

**Comment by dahlbyk** [comment]
> Did you have an idea to fix that ? I have the same problem but I need to use LocalPlugin.

Check out https://github.com/GriddleGriddle/Griddle/pull/771. Until that ships, you should be able to roughly copy `PageDropdownEnhancer` into your own project.
