### ISSUE TITLE
Change & relocate the pageSizeSettings field

### ISSUE THREAD

**Issue by serkyen** [GriddleGriddle/Griddle#714]
## Griddle version
"griddle-react": "^1.3.1",

## Expected Behavior
I want to be able to create a component to replace the pageSizeSetting field. 

## Actual Behavior
I have managed to change the field into a drop down using one of the examples from the stories however, it is not really a component, but more like a function. Here is the code for the customized field...

```
import React, { Component } from 'react';
import Griddle, { actions, selectors, components, plugins, RowDefinition, ColumnDefinition} from 'griddle-react';
import { connect } from 'react-redux';
import compose from 'recompose/compose';
import mapProps from 'recompose/mapProps';
import getContext from 'recompose/getContext';
import withContext from 'recompose/withContext';
import withHandlers from 'recompose/withHandlers';
import withState from 'recompose/withState';


const pageSizeSettings = () =>
  compose(
    connect(
      (state) => ({
        pageSize: selectors.pageSizeSelector(state),
      }),
      {
        setPageSize: actions.setPageSize
      }
    ),
    withHandlers({
      onChange: props => e => {
        props.setPageSize(+e.target.value);
      },
    }),
  )(({ pageSize, onChange }) => {

    const pageSizes = [5, 10, 20, 50]
  return (
    <div>
      Number of Items:
      <select onChange={onChange} defaultValue={10}>
        { pageSizes.map(s => <option key={s}>{s}</option>) }
      </select>
    </div>
  )});

export default pageSizeSettings;

```

I use it like this...

```
import pageSizeSettings from '../global/PageSizeSettings';
...
SettingsComponents: {
   pageSizeSettings: pageSizeSettings(),
},
```

What I want is to use it like this...
```
SettingsComponents: {
   pageSizeSettings: <pageSizeSettings />,
},
```

My main reason for this is so that I can use the component in the Layout and put it where I want to. I have looked in the stories but can't find any clues on how to both change the field, and move it at the same time. I have tried doing this but it doesn't work...

```
const PageSizeDropDownInPaginationPlugin = {
      components: {
        Pagination: ({ Next, Previous, PageDropdown }) => (
          <div>
            {pageSizeSettings()}
            {Previous && <Previous />}
            {PageDropdown && <PageDropdown /> }
            {Next && <Next /> }
          </div>
        ),
      },
    };
```

I realise this is more of a 'lack of react knowledge' type of issue but I have tried everything to try to convert the first block of code into a component to no avail. It's the compose and connect parts that is confusing to me. I just want a simple drop down component that can use the actions.setPageSize but can't get it to work.

Any help would really be appreciated.
Thanks in advance.

**Comment by dahlbyk** [comment]
> It's the compose and connect parts that is confusing to me.

Completely understandable. Honestly, I've started helping with this project to force myself to learn these better. Griddle heavily leverages [recompose](https://github.com/acdlite/recompose):

  > Recompose focuses on another unit of composition: higher-order components (HoCs). HoCs are functions that accept a base component and return a new component with additional functionality. They can be used to abstract common tasks into reusable pieces.

In this case, your "base component" is `({ pageSize, onChange }) => { ... }`) and the "additional functionality" is that it doesn't need any external `props` to work (i.e. when we're done we can call `<PageSizeSettings />` alone). How?

* `compose` chains multiple higher-ordered components together, returning a function that itself is a higher-ordered component. We're immediately invoking that function to "wrap" your base component.
  * `connect` injects `props` from the [Redux](http://redux.js.org/docs/basics/UsageWithReact.html) store.
  * `withHandlers` adds an `onChange` click handler based on `props` from `connect()`.

The JSX quirk that you may be missing is that components have to be capitalized:

```javascript
import pageSizeSettings from '../global/PageSizeSettings';

const PageSizeSettings = pageSizeSettings();

const PageSizeSettingsInLayoutPlugin = {
  components: {
    Layout: ({ ... }) => (
      <div>
        <PageSizeSettings />
        ...
      </div>
    ),
  },
  settingsComponentObjects: {
    pageSizeSettings: null,
  }
}
```

**Note:** The example you copied uses a function that returns a component so it can accept configuration. If no configuration is needed, you can export/import the component directly:

```javascript
const PageSizeSettings =
  compose(
    connect(...),
    withHandlers(...)
  )(props => (
    ...
  ));

export default PageSizeSettings;
```

and

```javascript
import PageSizeSettings from '../global/PageSizeSettings';

// <PageSizeSettings /> should work
```

I'm going to go ahead and close this, since it's not a Griddle issue, but feel free to comment if you need additional clarification. You could also get some [Stack Overflow rep](https://stackoverflow.com/questions/tagged/griddle) out of this sort of question.

**Comment by serkyen** [comment]
@dahlbyk Thank you for that. Explains a lot. 

I managed to get it to work :)

> The example you copied uses a function that returns a component so it can accept configuration. If no configuration is needed, you can export/import the component directly

Can you please explain this in a little more detail? 

So I changed `const PageSizeSettings = () =>` to `const PageSizeSettings =` and it worked. 

Where does 'configuration' come into it?
Do you just mean passing arguments in?

Thanks

**Comment by dahlbyk** [comment]
Yes, I just mean passing arguments in, both to the plugin and through to `pageSizeSettings`:

```javascript

    const PageSizeDropDownPlugin = (config) => ({
      components: {
        SettingsComponents: {
          pageSizeSettings: pageSizeSettings(config),
        },
      },
    });


    const pluginConfig = {
      pageSizes: [5, 10, 20, 50],
    };
    <Griddle ... plugins=[PageSizeDropDownPlugin(pluginConfig), ...] ... />
```

**Comment by serkyen** [comment]
@dahlbyk Ok I understand :) Thanks again!
