### ISSUE TITLE
External functions documentation clarification

### ISSUE THREAD

**Issue by 0xdabbad00** [GriddleGriddle/Griddle#79]
On `http://dynamictyped.github.io/Griddle/externalData.html` it would be nice to see what the function declaration format should be for the variables.  For example at the very top under the heading `Wrapper Component (recommended)` the variable `externalChangeSort` just says it needs to be set to a function, but specifically it should say that it needs to be set to a function of form `changeSort: function(sort, sortAscending)` so users know the function receives two variables, and it should be identified that `sort` is the column name and `sortAscending` is either 1 or 0?

**Comment by ryanlanciaux** [comment]
I realize this issue is from a really long time ago. There has been some update to the 0.x documentation that has addressed a bit of this. Additionally we just released 1.0 and have documented these types of methods here. http://griddlegriddle.github.io/Griddle/docs/api/ 

We will be doing a much better job of keeping 1.0 (and beyond) documentation up-to-date. Closing this one for now but please feel free to open issues for any problems that are encountered.
