### ISSUE TITLE
Convert Data + Filters to use Flux Stores

### ISSUE THREAD

**Issue by ryanlanciaux** [GriddleGriddle/Griddle#92]
After thinking about how data is going to be shared between components with the introduction of column filters (that might get way more complex), using Flux seems like it would be an ideal solution.

**Comment by scvnc** [comment]
It's interesting to take a note with how Facebook's grid is handling this-- it doesn't implement filtering/sorting/(pagination ?) on the grid component. It just takes a dataset and renders it in grid-- everything else is out of scope. I really like that idea because it's a clear separation of concerns and it opens the door for any kind of architecture be it flux or otherwise. If users don't want to write their own custom paging/sorting then generic data adapters can be provided that can wrap the grid.

**Comment by ryanlanciaux** [comment]
I'm going to close this for now since it should technically be under the [Griddle Core](https://github.com/GriddleGriddle/griddle-core) project.
